import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Application",
    projects: [
        "Projects/DipQuizApp",
        "Projects/DipQuizHostApp"
    ],
    schemes: [],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
