import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Application",
    projects: [
        "Projects/DipQuizApp",
        "Projects/DipQuizHostApp"
    ],
    schemes: [
        Scheme(
            name: "DipQuizApp",
            buildAction: .buildAction(targets: [
                .project(path: "Projects/DipQuizApp", target: "DipQuiz")
            ])
        ),
        Scheme(
            name: "DipQuizHostApp",
            buildAction: .buildAction(targets: [
                .project(path: "Projects/DipQuizHostApp", target: "DipQuizHost")
            ])
        )
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
